const mongoose = require('mongoose');

const registrationSchema = new mongoose.Schema({
  firstName: { type: String, required: true },
  lastName: { type: String, required: true },
  birthDate: { type: Date, required: true },
  streetAddress: { type: String, required: true },
  streetAddress2: String,
  city: { type: String, required: true },
  state: { type: String, required: true },
  zipCode: { type: String, required: true },
  phoneNumber: { type: String, required: true },
  email: { type: String, required: true },
  emergencyName: { type: String, required: true },
  emergencyPhone: { type: String, required: true },
  height: { type: Number, required: true },
  weight: { type: Number, required: true },
  goalWeight: Number,
  bloodType: String,
  healthIssues: String,
  medications: String,
  smoke: Boolean,
  surgery: Boolean,
  alcohol: Boolean,
  supplements: Boolean,
  foodTracking: Boolean,
  proSport: Boolean,
  exercisePain: Boolean,
  nightEating: { type: Number, min: 0, max: 5 },
  breakfastFrequency: { type: Number, min: 0, max: 5 },
  nutritionRating: { type: Number, min: 0, max: 5 },
  exerciseDays: [String],
  exerciseTime: String,
  trainingGoals: [String],
  eatingReasons: [String],
  membershipType: String,
  exerciseDuration: { type: Number, min: 1, max: 12 },
  startMonth: String,
  signature: { type: String, required: true },
  createdAt: { type: Date, default: Date.now },
});

module.exports = mongoose.models.Registration || mongoose.model('Registration', registrationSchema);